{
                "作者": "呕吼",
                "站名": "红果短剧",
                "请求头": "User-Agent@Mozilla/5.0 (Linux；； Android 9；； ASUS_I003DD Build/PI；； wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36&&Cookie@Hm_lvt_b7b8b64a02a5be0507f0c46011515b2b=1772677836；； HMACCOUNT=17BED804ED862610；； tackStats42615=1；； PHPSESSID=rhvlkmot07ad3e1bissc7gv154；； Hm_lpvt_b7b8b64a02a5be0507f0c46011515b2b=1772762863&&Accept@text/html,application/xhtml+xml,application/xml；；q=0.9,image/avif,image/webp,image/apng,*/*；；q=0.8,application/signed-exchange；；v=b3；；q=0.7&&Accept-Language@zh-CN,zh；；q=0.9",
                "编码": "UTF-8",
                "图片代理": "0",
                "直接播放": "0",
                "播放请求头": "",
                "嗅探词": ".mp4#.m3u8#.flv#hcts-m3u8#index.m3u8",
                "免嗅": "1",
                "过滤词": "",
                "主页url": "https://www.hgdj.app/",
                "首页": "120",
                "起始页": "1",
                "分类url": "https://www.hgdj.app/vodshow/{cateId}--------{catePg}---{year}.html",
                "分类": "电影$dianying#电视剧$dianshiju#动漫$dongman#短剧$duanju#",
                "二次截取": "",
                "数组": "hl-item-thumb hl-lazy&&</a>",
                "标题": "title=\"&&\"",
                "图片": "data-original=\"&&\"",
                "副标题": "<span class=\"hl-lc-1 remarks\">&&</span>",
                "链接": "href=\"&&\"",
                "影片年代": "年份：&&</li>",
                "影片地区": "地区：&&</li>",
                "影片类型": "类型：&&</li>",
                "状态": "状态：&&</li>",
                "导演": "导演：&&</li>",
                "主演": "主演：&&</li>",
                "简介": "简介：&&</div>",
                "线路二次截取": "",
                "线路数组": "<a class=\"hl-tabs-btn hl-slide-swiper&&/a>",
                "线路标题": "</i>&&<",
                "播放二次截取": "",
                "播放数组": "<ul class=\"hl-plays-list hl-sort-list&&</ul>",
                "倒序": "0",
                "播放列表": "<a&&</a>",
                "播放标题": ">&&</a>",
                "播放链接": "href=\"&&\"",
                "解析": "",
                "跳转播放链接": "var player_*\"url\":\"&&\"",
                "跳转解析": "",
                "搜索请求头": "User-Agent$MOBILE_UA",
                "搜索url": "https://www.hgdj.app/vodsearch/{wd}----------{pg}---.html",
                "搜索模式": "1",
                "搜索后缀": "",
                "搜索二次截取": "",
                "搜索数组": "hl-item-thumb hl-lazy&&</a>",
                "搜索标题": "title=\"&&\"",
                "搜索图片": "data-original=\"&&\"",
                "搜索副标题": "<span class=\"hl-lc-1 remarks\">&&</span>",
                "搜索链接": "href=\"&&\"",
                "筛选": "1",
                "类型": "",
                "剧情": "喜剧&爱情&恐怖&动作&科幻&剧情&战争&警匪&犯罪&动画&奇幻&武侠&冒险&枪战&恐怖&悬疑&惊悚&经典&青春&文艺&微电影&古装&历史&运动&农村&儿童&网络电影",
                "剧情值": "*",
                "地区": "大陆&香港&台湾&美国&法国&英国&日本&韩国&德国&泰国&印度&意大利&西班牙&加拿大&其他",
                "地区值": "*",
                "年份": "1950-2026",
                "年份值": "*",
                "语言": "国语&英语&粤语&闽南语&韩语&日语&法语&德语&其它",
                "语言值": "*",
                "字母": "A&B&C&D&E&F&G&H&I&J&K&L&M&N&O&P&Q&R&S&T&U&V&W&X&Y&Z&0-9",
                "字母值": "*",
                "排序": "时间&人气&评分",
                "排序值": "time&hits&score"
            }