var rule = {
            title: 'M1949电影',
            host: 'https://sosexxx.com',
            url: '/index.php/vod/show/id/fyclass/page/fypage.html',
            searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
            searchable: 2,
            quickSearch: 0,
            filterable: 0,
            filter: '',
            filter_url: '',
            filter_def: {},
            headers: {
                'User-Agent': 'MOBILE_UA',
            },
            timeout: 5000,
            class_parse: '.nav-m-wrapper&&li:lt(5);a&&Text;a&&href;(\\d+)',
            cate_exclude: '',
            play_parse: true,
            //lazy: def_lazy,
            double: true,
            推荐: '*',
            一级: 'ul.row&&li;a&&title;.lazyload&&data-original;.item-status&&Text;a&&href;详情',
            二级: {
                title: 'h3&&a&&Text;p.row&&span&&Text',
                img: '.lazyload&&data-original',
                desc: 'p.row&&span:eq(5)&&Text;p.row&&span:eq(2)&&Text;p.row&&span:eq(1)&&Text;p.row&&span:eq(4)&&Text;p.row&&span:eq(3)&&Text',
                content: '.text.text-row&&Text',
                tabs: '.swiper-wrapper li',
                lists: '.ewave-playlist-content:eq(#id)&&li',
                tab_text: 'body&&Text',
                list_text: 'body&&Text',
                list_url: 'a&&href',
            },
            搜索: '*',
        }